name: Upload Python Package to PyPi
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: python setup.py install
      - name: Run unit tests
        run: python -m pytest --cov=tests/

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test

    steps:
      - name: Check out repository code
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U setuptools_scm wheel twine
          python setup.py install
    # If PyPi is wished
    #- name: Build and publish
    #  env:
    #    TWINE_USERNAME: __token__
    #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #  run: |
    #    python setup.py sdist bdist_wheel
    #    twine upload dist/*
